### PR TITLE
add hashlink support

### PR DESCRIPTION
**Pull request by ConstNW**
Depends on PRs:
HaxeFoundation/hashlink#338
HaxeFoundation/haxe#9048

### CODE REVIEW

**Comment by jonasmalacofilho** [comment]
That's awesome @ConstNW.  I'll try to review & test this during the weekend.

I see you fixed some SQLite issues.  How about MySQL, last time I tried there were some problems with it too.

**Comment by ConstNW** [comment]
@jonasmalacofilho, I'll take a look at mysql later

**Comment by ConstNW** [comment]
can be merged, all tests are passed on HL target
```
$ hl test.hl mysql://spod:@192.168.1.3/test
utest/ui/text/PrintReport.hx:52: 
assertations: 296
successes: 296
errors: 0
failures: 0
warnings: 0
execution time: 2.055

results: ALL TESTS OK (success: true)
MysqlTest
  testBoolean: OK .......
  testData: OK ........
  testDateQuery: OK ........
  testEnum: OK .........
  testIssue19: OK .
  testIssue34: OK ...
  testIssue3828: OK ..
  testIssue6: OK ..
  testIssue6041: OK ..
  testNull: OK ........................................
  testSpodTypes: OK .....................................
  testStringConcatenation: OK .
  testStringIdRel: OK .............
  testUpdate: OK ...............
SqliteTest
  testBoolean: OK .......
  testData: OK ........
  testDateQuery: OK ........
  testEnum: OK .........
  testIssue19: OK .
  testIssue34: OK ...
  testIssue3828: OK ..
  testIssue6: OK ..
  testIssue6041: OK ..
  testNull: OK ........................................
  testSpodTypes: OK .....................................
  testStringConcatenation: OK .
  testStringIdRel: OK .............
  testUpdate: OK ...............
```

**Comment by jonasmalacofilho** [comment]
Thanks @ConstNW !

**Pull request merged**
